---
title: "STAA-566-ggplot2"
author: "Sarah Marcrum"
date: '2022-09-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(ggplot2)
library(ggsankey)
library(dplyr)
library(teamcolors)
```

+ link to data source: https://www.pro-football-reference.com/teams/kan/2021_advanced.htm#advanced_receiving

+ helpful links:  
https://rpubs.com/techanswers88/sankey-with-own-data-in-ggplot
<br> https://r-charts.com/color-palette-generator/

```{r}
#read in data (had to split download into two parts due to website limitations)
targets_2021 <- read_excel("chiefs_targets_2021.xlsx")

head(targets_2021)
```

```{r}
#cleaning and preparing data
# standardize position field
targets_2021 <- targets_2021 %>% mutate(Pos = toupper(Pos))

#correct Jody Fortson's name and position
targets_2021 <- targets_2021 %>% mutate(Player = replace(Player, Player == "Joe Fortson", "Jody Fortson"))
targets_2021 <- targets_2021 %>% mutate(Pos = replace(Pos, Player == "Joe Fortson", "TE"))

#correct Michael Burton's position
targets_2021 <- targets_2021 %>% mutate(Pos = replace(Pos, Player == "Michael Burton", "FB"))

head(targets_2021)
```

```{r}
# format data for sankey diagram
#drop the team total row
targets_2021 <- targets_2021[-17,]

#the first node will be the total number of passes on the team
targets_2021 <- targets_2021 %>% mutate(Total = "Total Targets")

#rename position category
targets_2021 <- targets_2021 %>% rename(Position = Pos)

#nodes
sankey_cat <- targets_2021 %>% make_long(Total, Position, Player)

```

```{r}
#format player and target data for sankey
dfa <- sankey_cat %>% filter(x == 'Player')

dfa <- merge(dfa, targets_2021[, c("Player", "Tgt")], by.x = 'node', by.y = 'Player' )

#rename column
dfa <- dfa %>% rename(n = Tgt)

############################
#get positional totals
dfb <- sankey_cat %>% filter(x == 'Position')

dfb_agg <- targets_2021 %>% 
  group_by(Position) %>%
  summarise(n = sum(Tgt))

dfb <-  merge(dfb, dfb_agg, by.x = 'node', by.y = 'Position', all.x = TRUE)

###########################
#get team totals
dfc <- sankey_cat %>% filter(x == 'Total')

dfc_agg <- targets_2021 %>%
  group_by(Total) %>%
  summarise(n = sum(Tgt))

dfc <-  merge(dfc, dfc_agg, by.x = 'node', by.y = 'Total', all.x = TRUE)

###########################
#join tables
dfd <- rbind(dfc, dfb, dfa)


```




```{r}
#sankey diagram targets(total) > target position > player

pl <- ggplot(dfd, aes(x = x
                      , next_x = next_x
                      , node = node
                      , next_node = next_node
                      , fill = factor(node)
                      
                      , label = paste0(node," ", n)
)
)

pl <- pl +geom_sankey(flow.alpha = 0.5,  color = "gray40", show.legend = TRUE, node.color =1)
pl <- pl +geom_sankey_label(size = 3, color = "white", fill= "gray40", hjust = -0.2)


pl <- pl + theme_sankey(base_size = 16)

pl <- pl + theme(legend.position = "none")
pl <- pl +  theme(axis.title = element_blank()
                  , axis.text.y = element_blank()
                  , axis.ticks = element_blank()  
                  , panel.grid = element_blank()
                  , panel.spacing.x=unit(-10, "lines")
                  , plot.caption = element_text(size = 8)
                  )

#move x axis labels to top
pl <- pl + scale_x_discrete(position = "top") 


#set custom colors for each node
pl <- pl + scale_fill_manual(values = c(
  'Total Targets' = '#000000',
  'WR' = '#e31837',
  'TE' = '#ec5335',
  'T' = '#f16a32',
  'FB' = '#FFB81C',
  'RB' = "#fb9f27",
  #WR
  'Tyreek Hill*' = '#e31837',
  "Mecole Hardman" = "#e83f58",
  "Byron Pringle" = "#ec657a",
  "Demarcus Robinson" = "#f18c9b", 
  "Josh Gordon" =  "#f6b2bc",
  "Marcus Kemp" =  "#fad9de",
  #TE
  'Travis Kelce*' ="#ec5335", 
  'Noah Gray' = "#ef7057", 
  "Jody Fortson"  = "#a76a1a",
  "Blake Bell" = "#f9c6bc",   
  #T
  'Mike Remmers' = "#f16a32", 
  #RB
  "Clyde Edwards-Helaire" = "#fb9f27",
  "Darrel Williams" = "#d18521",
  "Jerick McKinnon" =  "#d99946",     
  "Derrick Gore" = "#d99946",         
  #FB       
  "Michael Burton" =  "#FFB81C"   
  ))

#titles and labels
pl <- pl + labs(title = "Kansas City Chiefs Pass Targets")
pl <- pl + labs(subtitle = "2021 Regular Season")
pl <- pl + labs(caption = "* Selected to Pro Bowl") #caption from data source
pl <- pl + labs(fill = 'Nodes')
```


```{r, fig.width=10}
print(pl)
```

+ Notes:

I would like to have been able to sort the players by number of targets, but I was unable to find a way to do so that worked with the ggsankey package; this seems to be a known issue, see https://github.com/davidsjoberg/ggsankey/issues/7



